image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
    command: npx ts-node scripts/sample2.ts

vscode:
  extensions:
    - humao.rest-client@0.24.2:tiNIwP71m33jcKqZcyO2EQ==
    - dendron.dendron-markdown-preview-enhanced@0.10.2:t6XDgLDP/TtMhcw6PIWfQA==