image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
    command:  while true; do npx ts-node scripts/signed_assertion_from_env_privkey.ts; sleep 270; done 

vscode:
  extensions:
    - humao.rest-client@0.24.2:tiNIwP71m33jcKqZcyO2EQ==
    - dendron.dendron-markdown-preview-enhanced@0.10.2:t6XDgLDP/TtMhcw6PIWfQA==