
# @name gettoken

POST {{api_url}}/v2/auth/token 
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer
&client_assertion=eyJhbGciOiJSUzM4NCIsImtpZCI6IjIwMjAtMTEtMDRUMjM6MDg6MDEuNzU2WiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJldGlkcm9uaWMtaW5mYXJjdHMtMjc2NSIsInN1YiI6ImV0aWRyb25pYy1pbmZhcmN0cy0yNzY1IiwiYXVkIjoiaHR0cHM6Ly9hcGkucmVkb3hlbmdpbmUuY29tL3YyL2F1dGgvdG9rZW4iLCJpYXQiOjE2MDQ1MzI5NjAsImV4cCI6MTYwNDUzMzI2MCwianRpIjoicmVkb3gxNjA0NTMyOTYwOTI3Iiwic2NvcGVzIjpbXX0.oc5XcYJCkpMUP7t6S2hzeril12GDOH_LnQtIsnQBqs37uF8UNk8h1DDmkali4P22LGlMIfIQKFkSEbIgU8UYLuGSBdF5c8MsgQ3WEswh-_Pe6ZHsGWElsiGN-qUa1kT8sPN-8U7MFGc8MWRlvqR_yqTpoPzTVo0b902AcLkyo3pXnW2Bo5IoOBYL5YCoAm6VxWPHMJsm-ku6htko8pZQWgFirzjUgwxxbIFrtJo1RRANtHusC_LIgnOOKcrpAmGfQsUV9rMGKUMlgDzZHsbntJkaTJhvMp_18CxCyYbUpELEg4TaXebX8F3O7cciNgSDDgEi0gAwrGs4luZkJZcARA
&client_id=etidronic-infarcts-2765
&alg=RS384
&kid=etidronic-infarcts-2765
&typ=JWT


###

GET {{api_url}}/v2/fhirenvironment
# Authorization: //# Bearer {{$dotenv %ACCESS_TOKEN}}
Authorization: Bearer {{gettoken.response.body.$.access_token}}
